---
settings:
  name: E-Series
  platform: cloud
  internal:
    pdf_enabled: true
  prod:
    pdf_enabled: true
    harmony_enabled: false
  langs: es-es,us-en,de-de,fr-fr,it-it,pt-br,ja-jp,ko-kr,zh-cn,zh-tw
sidebar:
  entries:
  - title: Documentos de la serie E
    url: "/index.html"
  - title: Notas de la versión
    entries:
    - title: Qué hay de nuevo
      url: "/whats-new.html"
  - title: Empezar
    entries:
    - title: Descubra los sistemas de la Serie E
      url: "/task-discover-e-series.html"
  - title: Administrar sistemas de la Serie E
    entries:
    - title: Visualice sus sistemas de la Serie E
      url: "/task-view-e-series.html"
    - title: Eliminar un sistema de la NetApp Console
      url: "/task-remove-e-series.html"
  - title: Conocimiento y apoyo
    entries:
    - title: Regístrese para recibir asistencia
      url: "/task-support-registration.html"
    - title: Obtener ayuda
      url: "/task-get-help.html"
  - title: Avisos legales
    url: "/legal-notices.html"
product-family:
  name: Storage Management
  repo: storage-management-family
