---
sidebar: sidebar 
permalink: task-discover-e-series.html 
keywords: e-series, cluster, discover, manage, discovering, discover e-series 
summary: La NetApp Console puede descubrir los sistemas E-Series en su entorno local.  Al agregar sistemas de la Serie E a la consola, podrá obtener una vista completa de los datos en su entorno híbrido de múltiples nubes. 
---
= Descubra los sistemas de la Serie E
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Agregar sistemas E-Series a la NetApp Console le permite administrar sus sistemas E-Series desde la consola y obtener una vista completa de su infraestructura de datos en su entorno híbrido de múltiples nubes.

.Rol de NetApp Console requerido
Administrador de la organización, administrador de carpetas o proyectos, administrador de almacenamiento o especialista en estado del sistema. link:https://docs.netapp.com/us-en/bluexp-setup-admin/reference-iam-predefined-roles.html["Obtenga información sobre los roles de acceso a la NetApp Console ."^]

.Antes de empezar
Necesitarás lo siguiente:

* Un agente de NetApp Console instalado en un proveedor de nube o en tus instalaciones, con conectividad de red al sistema E-Series. Debes tener el rol de administrador de organización para instalar un agente de Console. Si no sabes si tu organización tiene un agente de Console, o si necesitas que se cree uno, contacta a tu administrador de Console. https://docs.netapp.com/us-en/bluexp-setup-admin/task-user-settings.html#contact-admin["Comuníquese con el administrador de su organización."^]
* El nombre de dominio o la dirección IP del controlador del sistema de almacenamiento.
* Credenciales de administrador para el sistema E-Series.


.Pasos
. Desde el menú de navegación, seleccione *Almacenamiento > Administración*.
. Desde la página *Sistemas*, seleccione *Agregar* y seleccione *En las instalaciones*.
. Junto a *E-Series*, seleccione *Descubrir*.
. En la página _Detalles del clúster de la serie E_, ingrese el nombre de dominio o la dirección IP del controlador del sistema de almacenamiento, las credenciales de administrador para el sistema y luego seleccione *Agregar*.

