---
sidebar: sidebar 
permalink: whats-new.html 
keywords: 'what"s new, features, new, release notes, bugs, limitations, known issues, enhancements, fixes, e-series' 
summary: Conozca las novedades en la administración de sistemas E-Series en BlueXP. 
---
= Novedades en la gestión de la Serie E
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Descubra las novedades en la gestión de sistemas E-Series en la consola de NetApp .



== 06 de octubre de 2025



=== BlueXP ahora es NetApp Console

La consola NetApp , construida sobre la base BlueXP mejorada y reestructurada, proporciona una gestión centralizada del almacenamiento NetApp y de los servicios de datos NetApp en entornos locales y en la nube a nivel empresarial, brindando información en tiempo real, flujos de trabajo más rápidos y una administración simplificada, que es altamente segura y compatible.

Para obtener más detalles sobre lo que ha cambiado, consulte lalink:https://docs.netapp.com/us-en/bluexp-relnotes/index.html["Notas de la versión de la consola de NetApp"] .



== 12 de mayo de 2025



=== Se necesita el rol de acceso a BlueXP

Ahora necesita uno de los siguientes roles de acceso para ver, descubrir o administrar E-Series en BlueXP: administrador de la organización, administrador de carpeta o proyecto, administrador de almacenamiento o especialista en estado del sistema.  https://docs.netapp.com/us-en/bluexp/reference-iam-predefined-roles.html["Obtenga más información sobre los roles de acceso de BlueXP ."^]



== 18 de septiembre de 2022



=== Soporte para la Serie E

Ahora puede descubrir sus sistemas E-Series directamente desde BlueXP.  Descubrir los sistemas E-Series le proporciona una vista completa de los datos en su multinube híbrida.
